routes/web.php
<?php

use App\Http\Controllers\AbilityController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\BankTransactionController;
use App\Http\Controllers\BrokerController;
use App\Http\Controllers\CashController;
use App\Http\Controllers\CashTransactionController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ClassificationController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\StockTransactionController;
use App\Http\Controllers\ThirdPartyController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::view('/authenticate', 'auth.authenticate');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::view('/', 'home');

Route::resource('/abilities', AbilityController::class);
    Route::post('/abilities/search', [AbilityController::class, 'search'])->name('abilities.search');
    Route::get('/abilities/{abilitySlug}/restore', [AbilityController::class, 'restore'])->name('abilities.restore');

Route::resource('/roles', RoleController::class);
Route::get('/abilities/{roleSlug}/restore', [RoleController::class, 'restore'])->name('abilities.restore');

Route::resource('users', UserController::class);
    Route::post('/users/search', [UserController::class, 'search'])->name('users.search');
    Route::get('/users/{userSlug}/restore', [UserController::class, 'restore'])->name('users.restore');

Route::resource('/categories', CategoryController::class);
Route::resource('/classifications', ClassificationController::class);

Route::resource('/expenses', ExpenseController::class);
    Route::post('/expenses/search', [ExpenseController::class, 'search'])->name('expenses.search');

//Route::resource('/cash', CashController::class);
Route::get('/cash-transactions/receive', [CashTransactionController::class, 'receive']);
Route::get('/cash-transactions/create', [CashTransactionController::class, 'create']);
Route::resource('/cash-transactions', CashTransactionController::class)->only(['index', 'show']);
Route::resource('/banks', BankController::class);

Route::resource('banks', BankController::class);
    Route::post('/banks/search', [BankController::class, 'search'])->name('banks.search');
    Route::get('/banks/{bankSlug}/restore', [BankController::class, 'restore'])->name('banks.restore');

    Route::post('bank-transactions', BankTransactionController::class);
    Route::get('bank-transactions/{id}/create-journal', [JournalController::class, 'create'])
        ->name('bank-transactions.journals.create');

Route::resource('journals', JournalController::class);

Route::view('stock-transaction/buy', 'stocks.buy')->name('stock-transaction.buy.create');
//Route::post('stock-transaction/buy', [StockTransactionController::class, 'buy'])->name('stock-transaction.buy.store');
Route::view('stock-transaction/sell', 'stocks.sell')->name('stock-transaction.sell.create');
//Route::post('stock-transaction/sell', [StockTransactionController::class, 'sell'])->name('stock-transaction.sell.store');

Route::post('vendors', [ThirdPartyController::class, 'store']);

Route::resource('stock-transaction', StockTransactionController::class);
Route::resource('stocks', StockController::class)->only(['index', 'create', 'show', 'update']);
Route::resource('brokers', BrokerController::class)->only(['store']);

Route::view('profile', 'profile.show');

app/Models/CashTransaction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CashTransaction extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'journal_id',
        'description',
        'debit',
        'credit',
        'balance',
        'date',
        'recorded_at',
    ];

    protected $casts = [
        'date' => 'datetime',
    ];

    public function getIsRecordedAttribute()
    {
        return ! is_null($this->recorded_at);
    }

    public function journal()
    {
        return $this->belongsTo(Journal::class);
    }
}

app/Http/Controllers/CashTransactionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SearchRequest;
use App\Http\Requests\StoreCashRequest;
use App\Http\Requests\UpdateCashRequest;
use App\Models\Activity;
use App\Models\Cash;
use App\Models\CashTransaction;
use App\Models\ChartOfAccounts;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Str;

class CashTransactionController extends Controller
{
    public function index()
    {
        $cashTransactions = CashTransaction::withTrashed()->latest()->get();

        $activities = Activity::query()->where('subject_type', 'App\Models\CashTransaction')->limit(10)->latest()->get();

        return view('cash-transaction.index', compact('cashTransactions', 'activities'));
    }

//    /**
//     * Show the form for creating a new resource.
//     *
//     * @return Application|Factory|View|Response
//     * @throws AuthorizationException
//     */
//    public function create()
//    {
//        $this->authorize('create-cash-transaction');
//
//        return view('cash-transaction.create');
//    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function receive()
    {
        $accounts = ChartOfAccounts::all();

        return view('cash-transaction.receive', compact('accounts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        $accounts = ChartOfAccounts::all();

        return view('cash-transaction.spend', compact('accounts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreCashRequest $request
     * @return RedirectResponse
     */
    public function store(StoreCashRequest $request)
    {
        $cashTransaction = CashTransaction::create([
            'name' => ucfirst(strtolower($request->name)),
            'slug' => Str::slug($request->name),
        ]);

        return redirect()->action([self::class, 'show'], $cashTransaction)
            ->with('flash', $cashTransaction->name . ' has been added.');
    }

    /**
     * Display the specified resource.
     *
     * @param CashTransaction $cashTransaction
     * @return Application|Factory|View|Response
     */
    public function show(CashTransaction $cashTransaction)
    {
        return view('cash-transaction.show', compact('cashTransaction'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Cash $cashTransaction
     * @return Application|Factory|View|Response
     */
    public function edit(Cash $cashTransaction)
    {
        return view('cash-transaction.edit', compact('cash-transaction'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateCashRequest $request
     * @param Cash $cashTransaction
     * @return RedirectResponse
     */
    public function update(UpdateCashRequest $request, Cash $cashTransaction)
    {
        $cashTransaction->update([
            'name' => ucfirst(strtolower(str_replace('-', ' ', $request->name))),
            'slug' => Str::slug($request->name),
        ]);

        return redirect()->action([self::class, 'show'], $cashTransaction)
            ->with('flash', $cashTransaction->name . ' has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Cash $cashTransaction
     * @return RedirectResponse
     */
    public function destroy(Cash $cashTransaction)
    {
        return redirect()->action([self::class, 'index'])
            ->with('flash', $cashTransaction->name . ' deleted.');
    }

    public function restore($cashTransactionSlug)
    {
        $retrieve = CashTransaction::onlyTrashed()->where('slug', $cashTransactionSlug)->first();
        $retrieve->restore();

        return redirect()->action([self::class, 'index'])
            ->with('flash', $retrieve->name . ' has been restored.');
    }

    public function search(SearchRequest $request)
    {
        $q = $request->input('q');

        $cashTransaction = CashTransaction::query()
            ->where('name', 'LIKE', '%' . $q . '%')
            ->get();

        $archived = CashTransaction::onlyTrashed()
            ->where('name', 'LIKE', '%' . $q . '%')
            ->get();

        $all = $cashTransaction->merge($archived);

        session()->flash(
            'flash',
            $all->count() . ' ' . Str::plural('result', $all->count()) . '  found.'
        );

        return view('cash-transaction.index', compact('cash-transaction', 'archived'));
    }
}

resources/views/cash-transaction/_transactions.blade.php
<tr>
    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        {{ $bankTransaction->date->format('M j, Y') }}
    </td>

    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        @if($bankTransaction->is_recorded)
            {{--            {{ dd($bankTransaction->journal->first()) }}--}}
            <a href="{{ route('journals.show', $bankTransaction->journal->first()) }}">
                {{ $bankTransaction->description }}
            </a>
        @else
            <a href="{{ route('bank-transactions.journals.create', $bankTransaction) }}">
                {{ $bankTransaction->description }}
            </a>
        @endif

    </td>
    {{--    <a href="journals/create/{{ $bankTransaction }}">--}}
    {{--        {{ $bankTransaction->description }}--}}
    {{--    </a>--}}

    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        {{ number_format($bankTransaction->debit, 2) }}
    </td>

    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        {{ number_format($bankTransaction->credit, 2) }}
    </td>

    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        {{ number_format($bankTransaction->balance, 2) }}
    </td>
    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        <toggle-update
            :checked="{{ $bankTransaction->is_recorded ? 'true' : 'false' }}"
            :route="'banks'"
            :model="{{ $bank }}"
            :toggleable="false"
        >
        </toggle-update>
    </td>
{{--    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">--}}
{{--        @if($bankTransaction->is_recorded && $bankTransaction->is_reconciled)--}}
{{--            Reconciled <a href="">View</a>--}}
{{--        @elseif($bankTransaction->is_recorded && ! $bankTransaction->is_reconciled)--}}
{{--            <a href="" class="">Reconcile</a>--}}
{{--        @endif--}}
{{--    </td>--}}

</tr>

resources/views/cash-transaction/create.blade.php
<x-layout>
    <x-page-header>
        <div class="my-1">
            <h5 class="text-xl font-thin text-primary">
               Create New Expense
            </h5>
            <p class="max-w-2xl text-xs text-gray-500 text-left">
                <a href="{{ route('banks.index') }}" class="focus:outline-none"><i class="fas fa-arrow-left focus:outline-none"></i> Back to All Banks</a>
            </p>
        </div>
    </x-page-header>

    <x-container>
        <form action="{{ route('banks.store') }}" method="POST" autocomplete="off">
            @csrf
            <input type="hidden" autocomplete="false">
            <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                <div class="flex w-full justify-end items-center p-4">
                    <div class="flex">
                        <p class="shadow-sm mx-2">
                            <button class="focus:outline-none">
                                <i class="far fa-save py-2 px-3 shadow-sm bg-red-700 text-white rounded-sm"></i>
                            </button>
                        </p>
                    </div>
                </div>

                <div class="border-t border-gray-200">
                    <dl>
                        <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                            <dt class="text-xs font-medium text-gray-500">
                                Name
                            </dt>
                            <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                                <input
                                    name="particulars"
                                    placeholder="Lunch"
                                    class="w-11/12 p-2 focus:outline-none shadow-md rounded-md"
                                    value="{{ old('name') }}"
                                />
                                @if ($errors->has('name'))
                                    <small class="text-red-400 mx-2">{{ $errors->first('name') }}</small>
                                @endif
                            </dd>
                        </div>
                        <div class="bg-white p-4 grid grid-cols-3 gap-4">
                            <dt class="text-xs font-medium text-gray-500">
                                Account Number
                            </dt>
                            <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                                <input
                                    name="account_number"
                                    placeholder="200"
                                    class="w-11/12 p-2 focus:outline-none shadow-md rounded-md"
                                    value="{{ old('account_number') }}"
                                />
                                @if ($errors->has('account_number'))
                                    <small class="text-red-400 mx-2">{{ $errors->first('account_number') }}</small>
                                @endif
                            </dd>
                        </div>
                        <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                            <dt class="text-xs font-medium text-gray-500">
                                Account Name
                            </dt>
                            <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                                <input
                                    name="account_name"
                                    placeholder="Account Name"
                                    class="w-11/12 p-2 focus:outline-none shadow-md rounded-md"
                                    value="{{ old('account_name') }}"
                                />
                                @if ($errors->has('account_name'))
                                    <small class="text-red-400 mx-2">{{ $errors->first('account_name') }}</small>
                                @endif
                            </dd>
                        </div>
                    </dl>
                </div>
            </div>
        </form>
    </x-container>
</x-layout>

resources/views/cash-transaction/edit.blade.php
<x-layout>
    <x-page-header>
        <div class="my-1">
            <h5 class="text-xl font-thin text-primary">
                {{ ucfirst($bank->name) }}
            </h5>
            <p class="max-w-2xl text-xs text-gray-500 text-left">
                <a href="{{ route('banks.index') }}" class="focus:outline-none"><i class="fas fa-arrow-left focus:outline-none"></i> Back to All Banks</a>
            </p>
        </div>
    </x-page-header>

    <x-container>
        <form action="{{ route('banks.update', $bank) }}" method="POST" autocomplete="off">
            @csrf @method('PUT')
            <input type="hidden" autocomplete="false">
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            <div class="flex w-full justify-end items-center p-4">
                <div class="flex">
                    <p class="shadow-sm mx-2">
                      <button class="focus:outline-none">
                            <i class="far fa-save py-2 px-3 shadow-sm bg-red-700 text-white rounded-sm"></i>
                      </button>
                    </p>
                    <p class="shadow-sm"><i class="far fa-trash-alt py-2 px-4 shadow-sm bg-gray-100 rounded-sm"></i></p>
                </div>
            </div>
            <div class="border-t border-gray-200">
                <dl>
                    <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Bank
                        </dt>
                        <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                            <input
                                name="name"
                                placeholder=" "
                                class="w-11/12 p-2 focus:outline-none shadow-md rounded-md"
                                value="{{ old('name') ? old('name') : $bank->name }}"
                            />
                            @if ($errors->has('name'))
                                <small class="text-red-400 mx-2">{{ $errors->first('name') }}</small>
                            @endif
                        </dd>
                    </div>
                    <div class="bg-white p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Account Number
                        </dt>
                        <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                            <input
                                name="account_number"
                                placeholder=" "
                                class="w-11/12 p-2 focus:outline-none shadow-md rounded-md"
                                value="{{ old('account_number') ? old('account_number') : $bank->account_number }}"
                            />
                            @if ($errors->has('account_number'))
                                <small class="text-red-400 mx-2">{{ $errors->first('account_number') }}</small>
                            @endif
                        </dd>
                    </div>
                    <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Account Name
                        </dt>
                        <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                            <input
                                name="account_name"
                                placeholder=" "
                                class="w-11/12 p-2 focus:outline-none shadow-md rounded-md"
                                value="{{ old('account_name') ? old('account_name') : $bank->account_name }}"
                            />
                            @if ($errors->has('account_name'))
                                <small class="text-red-400 mx-2">{{ $errors->first('account_name') }}</small>
                            @endif
                        </dd>
                    </div>
                </dl>
            </div>
        </div>
        </form>
    </x-container>

    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
                <th scope="col" colspan="3"
                    class="px-2 md:px-6 py-3 text-left text-gray-500 uppercase tracking-tighter text-sm font-bolder">
                    Activity Logs
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($bank->activities as $activity)
                @include('partials._activities-list')
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-4 whitespace-nowrap">
                        <div class="flex items-center">
                            <div class="ml-4 text-xs">
                                No activities yet.
                            </div>
                        </div>
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>
</x-layout>

resources/views/cash-transaction/index.blade.php
<x-layout>
    <x-page-header>
        <div class="my-4">
            <h5 class="text-xl font-thin text-primary">
                <a href="{{ route('cash-transactions.index') }}" class="focus:outline-none pl-2">Cash Transactions</a>
            </h5>
            <x-search-form action="/cash-transactions/search" method="POST" role="search"/>
        </div>
        <div class="px-4 py-2 text-xs my-2 flex space-x-4">
            <a href="{{ url('cash-transactions/receive') }}" class="flex bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none">
                <div class="py-2 px-4 text-white font-bold">
                    Receive
                </div>
                <div class="bg-white px-3 flex flex-shrink-0 py-3">
                    <i class="fas fa-money-bill-wave fa-lg text-primary"></i>
                </div>
            </a>

            <a href="{{ url('cash-transactions/create') }}" class="flex bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none">
                <div class="py-2 px-4 text-white font-bold">
                    Spend
                </div>
                <div class="bg-white px-3 flex flex-shrink-0 py-3">
                    <i class="fas fa-comment-dollar fa-lg text-primary"></i>
                </div>
            </a>

        </div>
    </x-page-header>

    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200 text-xs">
            <thead class="bg-gray-100">
            <tr class="font-bolder text-left tracking-wider uppercase text-gray-700">
                <th scope="col" class="px-2 md:px-6 py-3">
                    Description
                </th>
                <th scope="col" class="px-2 md:px-6 py-3">
                    Debit
                </th>
                <th scope="col" class="px-2 md:px-6 py-3">
                    Credit
                </th>
                <th scope="col" class="px-2 md:px-6 py-3">
                    Balance
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($cashTransactions as $cashTransaction)
                <tr>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap">
                        <div class="flex items-center">
                            <div>
                                <div class="">
                                    <a class="focus:outline-none"
                                       href="{{ route('cash-transactions.show', $cashTransaction) }}">
                                        {{ ucfirst($cashTransaction->journal->description) }}
                                    </a>
                                </div>
                                <div class="text-gray-500">
                                    <small> Created {{ $cashTransaction->created_at->diffForHumans() }}</small>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
                        {{ number_format($cashTransaction->debit, 2) }}
                    </td>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
                        {{ number_format($cashTransaction->credit, 2) }}
                    </td>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
                        {{ number_format($cashTransaction->balance, 2) }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap" colspan="4">
                        No data yet.
                    </td>
                </tr>
            @endforelse

            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>

    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
                <th scope="col" colspan="3"
                    class="px-2 md:px-6 py-3 text-left text-gray-500 uppercase tracking-tighter text-sm font-bolder">
                    Activity Logs
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($activities as $activity)
                @include('partials._activities-list')
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-xs" colspan="3">
                        No activities yet.
                    </td>
                </tr>
            @endforelse
{{--            @if($activities->hasPages())--}}
{{--                <tr class="font-bolder text-left tracking-wider uppercase text-gray-700 text-sm">--}}
{{--                    <td class="px-2 md:px-6 py-2 whitespace-nowrap" colspan="3">--}}
{{--                        {{ $activities->links() }}--}}
{{--                    </td>--}}
{{--                </tr>--}}
{{--            @endif--}}
            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>
</x-layout>

resources/views/cash-transaction/receive.blade.php
<x-layout>
    <x-page-header>
        <div class="my-1">
            <h5 class="text-xl font-thin text-primary">
                Receive Cash on Hand
            </h5>
            <p class="max-w-2xl text-xs text-gray-500 text-left">
                <a href="{{ route('cash-transactions.index') }}" class="focus:outline-none"><i class="fas fa-arrow-left focus:outline-none"></i> Back to All Cash Transactions</a>
            </p>
        </div>
    </x-page-header>


    <receive-cash />

</x-layout>

resources/views/cash-transaction/show.blade.php
<x-layout>
    <x-page-header>
        <div class="my-1">
            <h5 class="text-xl font-thin text-primary">
                Cash
            </h5>
            <p class="max-w-2xl text-xs text-gray-500 text-left">
                <a href="{{ route('cash-transactions.index') }}" class="focus:outline-none pl-2"><i class="fas fa-arrow-left focus:outline-none"></i> Cash Transactions</a>
            </p>
        </div>
    </x-page-header>

    <x-container>
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            <div class="p-4">
                <div class="flex">
                    Transaction Details
                </div>
            </div>

            <div class="border-t border-gray-200">
                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            placeholder=" "
                            label="Particulars"
                            width="w-11/12 p-2"
                            readonly="readonly"
                            value="{{ number_format($cashTransaction->journal->amount, 2) }}"
                        ></x-input>
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            placeholder=" "
                            label="Running Balance"
                            width="w-11/12 p-2"
                            readonly="readonly"
                            value="{{ number_format($cashTransaction->balance, 2) }}"
                        ></x-input>
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            placeholder=" "
                            label="Description"
                            width="w-11/12 p-2"
                            readonly="readonly"
                            value="{{ $cashTransaction->journal->description }}"
                        ></x-input>
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            placeholder=" "
                            label="Date"
                            width="w-11/12 p-2"
                            readonly="readonly"
                            value="{{ $cashTransaction->date->format('M j, Y h:s a') }}"
                        ></x-input>
                    </div>
                </div>
            </div>
        </div>
    </x-container>

{{--    <x-container>--}}
{{--        --}}{{--slot begins here --}}
{{--        <table class="min-w-full divide-y divide-gray-200">--}}
{{--            <thead class="bg-gray-50">--}}
{{--            <tr>--}}
{{--                <th scope="col" colspan="3"--}}
{{--                    class="px-2 md:px-6 py-3 text-left text-gray-500 uppercase tracking-tighter text-sm font-bolder">--}}
{{--                    Activity Logs--}}
{{--                </th>--}}
{{--            </tr>--}}
{{--            </thead>--}}
{{--            <tbody class="bg-white divide-y divide-gray-200">--}}
{{--            @forelse ($bank->activities as $activity)--}}
{{--                @include('partials._activities-list')--}}
{{--            @empty--}}
{{--                <tr>--}}
{{--                    <td class="px-2 md:px-6 py-4 whitespace-nowrap">--}}
{{--                        <div class="flex items-center">--}}
{{--                            <div class="ml-4 text-xs">--}}
{{--                                No activities yet.--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </td>--}}
{{--                </tr>--}}
{{--            @endforelse--}}
{{--            </tbody>--}}
{{--        </table>--}}
{{--        --}}{{--slot ends here --}}
{{--    </x-container>--}}
</x-layout>

resources/views/cash-transaction/spend.blade.php
<x-layout>
    <x-page-header>
        <div class="my-1">
            <h5 class="text-xl font-thin text-primary">
               Create New Journal Entry
            </h5>
            <p class="max-w-2xl text-xs text-gray-500 text-left">
                <a href="{{ route('cash-transactions.index') }}" class="focus:outline-none"><i class="fas fa-arrow-left focus:outline-none"></i> Back to All Cash Transactions</a>
            </p>
        </div>
    </x-page-header>

    <x-container>
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">

            <create-journal
                :accounts="{{ $accounts }}"
            ></create-journal>

        </div>
    </x-container>
</x-layout>