routes/web.php
<?php

use App\Http\Controllers\AbilityController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\BankTransactionController;
use App\Http\Controllers\BrokerController;
use App\Http\Controllers\CashController;
use App\Http\Controllers\CashTransactionController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ClassificationController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\StockTransactionController;
use App\Http\Controllers\ThirdPartyController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::view('/authenticate', 'auth.authenticate');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::view('/', 'home');

Route::resource('/abilities', AbilityController::class);
    Route::post('/abilities/search', [AbilityController::class, 'search'])->name('abilities.search');
    Route::get('/abilities/{abilitySlug}/restore', [AbilityController::class, 'restore'])->name('abilities.restore');

Route::resource('/roles', RoleController::class);
Route::get('/abilities/{roleSlug}/restore', [RoleController::class, 'restore'])->name('abilities.restore');

Route::resource('users', UserController::class);
    Route::post('/users/search', [UserController::class, 'search'])->name('users.search');
    Route::get('/users/{userSlug}/restore', [UserController::class, 'restore'])->name('users.restore');

Route::resource('/categories', CategoryController::class);
Route::resource('/classifications', ClassificationController::class);

Route::resource('/expenses', ExpenseController::class);
    Route::post('/expenses/search', [ExpenseController::class, 'search'])->name('expenses.search');

//Route::resource('/cash', CashController::class);
Route::get('/cash-transactions/receive', [CashTransactionController::class, 'receive']);
Route::get('/cash-transactions/create', [CashTransactionController::class, 'create']);
Route::resource('/cash-transactions', CashTransactionController::class)->only(['index', 'show']);
Route::resource('/banks', BankController::class);

Route::resource('banks', BankController::class);
    Route::post('/banks/search', [BankController::class, 'search'])->name('banks.search');
    Route::get('/banks/{bankSlug}/restore', [BankController::class, 'restore'])->name('banks.restore');

    Route::post('bank-transactions', BankTransactionController::class);
    Route::get('bank-transactions/{id}/create-journal', [JournalController::class, 'create'])
        ->name('bank-transactions.journals.create');

Route::resource('journals', JournalController::class);

Route::view('stock-transaction/buy', 'stocks.buy')->name('stock-transaction.buy.create');
//Route::post('stock-transaction/buy', [StockTransactionController::class, 'buy'])->name('stock-transaction.buy.store');
Route::view('stock-transaction/sell', 'stocks.sell')->name('stock-transaction.sell.create');
//Route::post('stock-transaction/sell', [StockTransactionController::class, 'sell'])->name('stock-transaction.sell.store');

Route::post('vendors', [ThirdPartyController::class, 'store']);

Route::resource('stock-transaction', StockTransactionController::class);
Route::resource('stocks', StockController::class)->only(['index', 'create', 'show', 'update']);
Route::resource('brokers', BrokerController::class)->only(['store']);

Route::view('profile', 'profile.show');

app/Models/Stock.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Stock extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'user_id',
        'journal_id',
        'broker_id'
    ];

    public function activities()
    {
        return $this->morphMany(Activity::class, 'subject');
    }

    public function journal()
    {
        return $this->belongsTo(Journal::class);
    }

    public function broker()
    {
        return $this->belongsTo(Broker::class, 'broker_id');
    }
}

app/Http/Controllers/StockController.php
<?php

namespace App\Http\Controllers;

use App\Models\Activity;
use App\Models\Broker;
use App\Models\Stock;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class StockController extends Controller
{
    public function index()
    {
        $user = auth('web')->user();

        $stocks = $user->stockTransactions()->latest()
            ->paginate(config('expenses.paginate_count'));

        $brokers = $user->brokers;

        $shares = DB::table('stock_transactions as sh')
            ->where('user_id', auth('web')->id())
            ->select(DB::raw('stock as stock'), DB::raw('sum(shares) as total'))
            ->groupBy(DB::raw('stock'))
            ->get();

//        $profit = DB::table('stock_transactions as sh')
//            ->where('user_id', auth('web')->id())
//            ->where('type', 'SN')
//            ->select(DB::raw('stock as stock'), DB::raw('sum(gain) as total'))
//            ->groupBy(DB::raw('stock'))
//            ->get();

        //kunin lahat ng broker, foreach broker, go to stocks, sa stock kunin si journal, then sum the amount in journal
        $buyingPower = $user->brokers->map(function ($broker) {
            return collect($broker)->merge([
                'sum' => $broker->stockTransaction->sum(function ($stock) {
                    return $stock->total;
                }),
            ]);
        });

        $activities = Activity::query()->where('subject_type', 'App\Models\Stock')->limit(10)->latest()->get();

        return view('stocks.index', compact(
            'stocks',
            'activities',
            'brokers',
            'shares',
            'buyingPower',
        ));
    }

    public function update($stockId, Request $request)
    {
        $stock = Stock::find((int)$stockId);

        $broker = Broker::where('name', $request->broker)->first();

        if (!$broker) {
            return response()->json(['message' => 'Broker does not exist. Add first.'], 422);
        }

        $stock->update(['broker_id' => $broker->id]);

        return response()->json(['message' => 'Stock with ID: ' . ucfirst($stock->id) . ' has been updated.'], 200);
    }
}

resources/views/stocks/buy.blade.php
<x-layout>
    <x-page-header>
        <div class="my-4">
            <h5 class="text-xl font-thin text-primary">
                <a href="{{ route('stocks.index') }}" class="focus:outline-none pl-2">Stocks</a>
            </h5>
{{--            <x-search-form action="/stocks/search" method="POST" role="search"/>--}}

        </div>
    </x-page-header>
    <div class="text-primary text-center">
        @if (session()->has('flash'))
            <i class="fas fa-check-double"></i> {{ session()->get('flash') }}
        @endif
    </div>
    <x-container>
        {{--slot begins here --}}
        <form action="{{ route('stock-transaction.store') }}" method="POST">
            @csrf
            <input type="hidden" name="type" value="BN">
            <div class="border-t border-gray-200">
                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            name="stock"
                            placeholder=" "
                            label="Stock name"
                            width="w-11/12 p-2"
                            value="{{ old('stock') }}"
                            error="{{ $errors->first('stock') }}"
                        ></x-input>
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            name="shares"
                            placeholder=" "
                            label="Number of shares"
                            width="w-11/12 p-2"
                            value="{{ old('shares') }}"
                            error="{{ $errors->first('shares') }}"
                        ></x-input>
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            name="price"
                            placeholder=" "
                            label="Price"
                            width="w-11/12 p-2"
                            value="{{ old('price') }}"
                            error="{{ $errors->first('price') }}"
                        ></x-input>
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <options-without-autosave
                            :choices="{{ auth('web')->user()->brokers }}"
                            :label="'Broker'"
                            :name="'broker_id'"
                            :passed-value="'{{ old('broker_id') }}'"
                        ></options-without-autosave>

                        @if ($errors->has('broker_id'))
                            <small class="text-red-400 mx-2">{{ $errors->first('broker_id') }}</small>
                        @endif
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <button type="submit"
                                class="flex bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none">
                            <div class="py-1 px-4 text-white font-bold">
                                Save
                            </div>
                            <div class="bg-white px-3 flex flex-shrink-0 py-3">
                                <i class="far fa-save fa-lg text-primary"></i>
                            </div>
                        </button>
                    </div>
                </div>
            </div>
        </form>
        {{--slot ends here --}}
    </x-container>
</x-layout>

resources/views/stocks/index.blade.php
<x-layout>
    <x-page-header>
        <div class="my-4">
            <h5 class="text-xl font-thin text-primary">
                <a href="{{ route('stocks.index') }}" class="focus:outline-none pl-2">Stocks</a>
            </h5>
        </div>
        <div class="px-4 py-2 text-xs flex space-x-4 flex-wrap">

          <div class="w-24 my-2">
              <a href="{{ route('stock-transaction.buy.create') }}"
                 class="flex bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none">
                  <div class="py-2 px-4 text-white font-bold">
                      Buy
                  </div>
                  <div class="bg-white px-3 flex flex-shrink-0 py-3">
                      <i class="fas fa-money-bill-wave fa-lg text-primary"></i>
                  </div>
              </a>
          </div>

           <div class="w-24 my-2">
               <a href="{{ route('stock-transaction.sell.create') }}"
                  class="flex bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none">
                   <div class="py-2 px-4 text-white font-bold">
                       Sell
                   </div>
                   <div class="bg-white px-3 flex flex-shrink-0 py-3">
                       <i class="fas fa-comment-dollar fa-lg text-primary"></i>
                   </div>
               </a>
           </div>

            <add-new-broker></add-new-broker>

        </div>
    </x-page-header>

    <x-page-header>
        <div class="my-4 flex w-9/12 space-x-5">
            <div class="mt-5">
                <small>Shares Summary</small>
                <div class="grid grid-cols-12 bg-primaryLightest text-white">
                    <div class="col-span-6 text-center p-1 border-r">
                        Stock
                    </div>
                    <div class="col-span-6 text-center p-1">
                        Shares
                    </div>
                </div>
                <div class="grid grid-cols-12 text-gray-900">
                    @forelse($shares as $share)
                        @if ($share->total > 0)
                            <div class="col-span-6 text-center p-1 border-r border-b border-gray-400">
                                {{ $share->stock }}
                            </div>
                            <div class="col-span-6 text-center p-1 border-b border-gray-400">
                                {{  number_format($share->total) }}
                            </div>
                        @endif
                    @empty
                        <div class="col-span-12 text-gray-500 text-center p-1 border-r border-b border-gray-400">
                            <small>No stocks currently.</small>
                        </div>
                    @endforelse
                </div>
            </div>

            <div class="mt-5">
                <small>Buying Power</small>
                <div class="grid grid-cols-12 bg-primaryLightest text-white">
                    <div class="col-span-6 text-center border-r p-1">
                        Broker
                    </div>
                    <div class="col-span-6 text-center p-1">
                        BP
                    </div>
                </div>
                <div class="grid grid-cols-12 text-gray-900">
                    @forelse($buyingPower as $cash)
                        <div class="col-span-6 text-center p-1 border-r border-b border-gray-400">
                            {{ $cash['name'] }}
                        </div>
                        <div class="col-span-6 text-center p-1 border-b border-gray-400">
                            {{ number_format($cash['sum'], 2) }}
                        </div>
                    @empty
                        <div class="col-span-12 text-center p-1 border-b border-gray-400">
                            <small>No brokers currently</small>
                        </div>
                    @endforelse
                </div>
            </div>
        </div>

    </x-page-header>
    <div class="text-primary text-center">
        @if (session()->has('flash'))
            <i class="fas fa-check-double"></i> {{ session()->get('flash') }}
        @endif
    </div>
    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200 text-xs">
            <thead class="bg-gray-100">
            <tr class="font-bolder text-left tracking-wider uppercase text-gray-700">
                <th scope="col" class="px-2 md:px-6 py-3">
                    Description
                </th>
                <th scope="col" class="px-2 md:px-6 py-3">
                    Total
                </th>
                <th scope="col" class="px-2 md:px-6 py-3">
                    Broker
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($stocks as $stock)
                <tr>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap">
                        <div class="flex items-center">
                            <div>
                                <div class="">
                                    <a class="focus:outline-none"
                                       href="{{ route('stocks.show', $stock) }}">
                                        @switch($stock->type)
                                            @case('DE')
                                            Deposited.
                                            @break

                                            @case('BN')
                                            Bought {{ number_format($stock->shares) }} of {{ $stock->stock }}.
                                            @break

                                            @case('SN')
                                            Sold {{ number_format($stock->shares) * -1 }} of {{ $stock->stock }}.
                                            @break

                                            @case('WD')
                                            Withdrew.
                                            @break
                                        @endswitch

{{--                                        {{ ucfirst($stock->journal->description) }}--}}
                                    </a>
                                </div>
                                <div class="text-gray-500">
                                    <small> Created {{ $stock->created_at->diffForHumans() }}</small>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
                        {{ number_format($stock->total, 2) }}
                    </td>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
                        <options-with-model-update
                            :choices="{{ $brokers }}"
                            :route="'/brokers'"
                            :label="'Broker'"
                            :name="'broker'"
                            :passed-value="'{{ $stock->broker }}'"
                            :model="{{ $stock }}"
                            :edit-whole-entry="true"
                            :edit-route="'/stock-transaction'"
                        ></options-with-model-update>
                    </td>
                </tr>
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap" colspan="4">
                        No data yet.
                    </td>
                </tr>
            @endforelse

            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>

    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
                <th scope="col" colspan="3"
                    class="px-2 md:px-6 py-3 text-left text-gray-500 uppercase tracking-tighter text-sm font-bolder">
                    Activities
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($activities as $activity)
                @include('partials._activities-list')
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-xs" colspan="3">
                        No activities yet.
                    </td>
                </tr>
            @endforelse
            {{--            @if($activities->hasPages())--}}
            {{--                <tr class="font-bolder text-left tracking-wider uppercase text-gray-700 text-sm">--}}
            {{--                    <td class="px-2 md:px-6 py-2 whitespace-nowrap" colspan="3">--}}
            {{--                        {{ $activities->links() }}--}}
            {{--                    </td>--}}
            {{--                </tr>--}}
            {{--            @endif--}}
            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>
</x-layout>

resources/views/stocks/sell.blade.php
<x-layout>
    <x-page-header>
        <div class="my-4">
            <h5 class="text-xl font-thin text-primary">
                <a href="{{ route('stocks.index') }}" class="focus:outline-none pl-2">Stocks</a>
            </h5>
{{--            <x-search-form action="/stocks/search" method="POST" role="search"/>--}}
        </div>
    </x-page-header>

    <x-container>
        {{--slot begins here --}}
        <form action="{{ route('stock-transaction.store') }}" method="POST">
            @csrf
            <input type="hidden" name="type" value="SN">
            <div class="border-t border-gray-200">
                <div class="border-t border-gray-200">
                    <div class="p-4 grid grid-cols-3 gap-4">
                        <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                            <x-input
                                name="stock"
                                placeholder=" "
                                label="Stock name"
                                width="w-11/12 p-2"
                                value="{{ old('stock') }}"
                                error="{{ $errors->first('stock') }}"
                            ></x-input>
                        </div>
                    </div>

                    <div class="p-4 grid grid-cols-3 gap-4">
                        <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                            <x-input
                                name="shares"
                                placeholder=" "
                                label="Number of shares"
                                width="w-11/12 p-2"
                                value="{{ old('shares') }}"
                                error="{{ $errors->first('shares') }}"
                            ></x-input>
                        </div>
                    </div>

                    <div class="p-4 grid grid-cols-3 gap-4">
                        <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                            <x-input
                                name="price"
                                placeholder=" "
                                label="Price"
                                width="w-11/12 p-2"
                                value="{{ old('price') }}"
                                error="{{ $errors->first('price') }}"
                            ></x-input>
                        </div>
                    </div>

                    <div class="p-4 grid grid-cols-3 gap-4">
                        <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                            <options-without-autosave
                                :choices="{{ auth('web')->user()->brokers }}"
                                :label="'Broker'"
                                :name="'broker_id'"
                                :passed-value="'{{ old('broker_id') }}'"
                            ></options-without-autosave>

                            @if ($errors->has('broker_id'))
                                <small class="text-red-400 mx-2">{{ $errors->first('broker_id') }}</small>
                            @endif
                        </div>
                    </div>

                    <div class="p-4 grid grid-cols-3 gap-4">
                        <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                            <button type="submit"
                                    class="flex bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none">
                                <div class="py-1 px-4 text-white font-bold">
                                    Save
                                </div>
                                <div class="bg-white px-3 flex flex-shrink-0 py-3">
                                    <i class="far fa-save fa-lg text-primary"></i>
                                </div>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        {{--slot ends here --}}
    </x-container>
</x-layout>