routes/web.php
<?php

use App\Http\Controllers\AbilityController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\BankTransactionController;
use App\Http\Controllers\BrokerController;
use App\Http\Controllers\CashController;
use App\Http\Controllers\CashTransactionController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ClassificationController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\StockTransactionController;
use App\Http\Controllers\ThirdPartyController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::view('/authenticate', 'auth.authenticate');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::view('/', 'home');

Route::resource('/abilities', AbilityController::class);
    Route::post('/abilities/search', [AbilityController::class, 'search'])->name('abilities.search');
    Route::get('/abilities/{abilitySlug}/restore', [AbilityController::class, 'restore'])->name('abilities.restore');

Route::resource('/roles', RoleController::class);
Route::get('/abilities/{roleSlug}/restore', [RoleController::class, 'restore'])->name('abilities.restore');

Route::resource('users', UserController::class);
    Route::post('/users/search', [UserController::class, 'search'])->name('users.search');
    Route::get('/users/{userSlug}/restore', [UserController::class, 'restore'])->name('users.restore');

Route::resource('/categories', CategoryController::class);
Route::resource('/classifications', ClassificationController::class);

Route::resource('/expenses', ExpenseController::class);
    Route::post('/expenses/search', [ExpenseController::class, 'search'])->name('expenses.search');

//Route::resource('/cash', CashController::class);
Route::get('/cash-transactions/receive', [CashTransactionController::class, 'receive']);
Route::get('/cash-transactions/create', [CashTransactionController::class, 'create']);
Route::resource('/cash-transactions', CashTransactionController::class)->only(['index', 'show']);
Route::resource('/banks', BankController::class);

Route::resource('banks', BankController::class);
    Route::post('/banks/search', [BankController::class, 'search'])->name('banks.search');
    Route::get('/banks/{bankSlug}/restore', [BankController::class, 'restore'])->name('banks.restore');

    Route::post('bank-transactions', BankTransactionController::class);
    Route::get('bank-transactions/{id}/create-journal', [JournalController::class, 'create'])
        ->name('bank-transactions.journals.create');

Route::resource('journals', JournalController::class);

Route::view('stock-transaction/buy', 'stocks.buy')->name('stock-transaction.buy.create');
//Route::post('stock-transaction/buy', [StockTransactionController::class, 'buy'])->name('stock-transaction.buy.store');
Route::view('stock-transaction/sell', 'stocks.sell')->name('stock-transaction.sell.create');
//Route::post('stock-transaction/sell', [StockTransactionController::class, 'sell'])->name('stock-transaction.sell.store');

Route::post('vendors', [ThirdPartyController::class, 'store']);

Route::resource('stock-transaction', StockTransactionController::class);
Route::resource('stocks', StockController::class)->only(['index', 'create', 'show', 'update']);
Route::resource('brokers', BrokerController::class)->only(['store']);

Route::view('profile', 'profile.show');

app/Models/Bank.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Bank extends Model
{
    use HasFactory, SoftDeletes, RecordsActivity;

    protected $guarded = [];

    public function activities()
    {
        return $this->morphMany(Activity::class, 'subject');
    }

    public function transactions()
    {
        return $this->hasMany(BankTransaction::class);
    }

    public function balance()
    {
        if ($this->transactions()->exists()) {
            return $this->transactions()->latest()->first()->balance;
        } else {
            return 0;
        }
    }

    public function scopeDebit()
    {
        return $this->transactions()->whereNull('recorded_at')->sum('debit');
    }
}

app/Models/CashTransaction.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CashTransaction extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'journal_id',
        'description',
        'debit',
        'credit',
        'balance',
        'date',
        'recorded_at',
    ];

    protected $casts = [
        'date' => 'datetime',
    ];

    public function getIsRecordedAttribute()
    {
        return ! is_null($this->recorded_at);
    }

    public function journal()
    {
        return $this->belongsTo(Journal::class);
    }
}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SearchRequest;
use App\Http\Requests\StoreBankRequest;
use App\Http\Requests\UpdateBankRequest;
use App\Models\Bank;
use App\Models\Activity;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Str;

class BankController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function index()
    {
        $user = auth('web')->user();

        $banks = $user->banks;

        $activities = Activity::query()->where('subject_type', 'App\Models\Bank')->paginate(config('expenses.paginate_count'));

        return view('banks.index', compact('banks', 'activities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     */
    public function create()
    {
        return view('banks.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreBankRequest $request
     * @return RedirectResponse
     */
    public function store(StoreBankRequest $request)
    {
        $bank = Bank::create([
            'user_id' => auth('web')->id(),
            'name' => ucfirst(strtolower($request->name)),
            'account_number' => $request->account_number,
            'account_name' => $request->account_name,
            'slug' => Str::slug($request->name),
        ]);

        return redirect()->action([self::class, 'show'], $bank)
            ->with('flash', $bank->name . ' has been added.');
    }

    /**
     * Display the specified resource.
     *
     * @param Bank $bank
     * @return Application|Factory|View|Response
     */
    public function show(Bank $bank)
    {
        return view('banks.show', compact('bank'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Bank $bank
     * @return Application|Factory|View|Response
     */
    public function edit(Bank $bank)
    {
        return view('banks.edit', compact('bank'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateBankRequest $request
     * @param Bank $bank
     * @return RedirectResponse
     */
    public function update(UpdateBankRequest $request, Bank $bank)
    {
        $bank->update([
            'name' => ucfirst(strtolower($request->name)),
            'account_number' => $request->account_number,
            'account_name' => $request->account_name,
            'slug' => Str::slug($request->name),
        ]);

        return redirect()->action([self::class, 'show'], $bank)
            ->with('flash', $bank->name . ' has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Bank $bank
     * @return RedirectResponse
     */
    public function destroy(Bank $bank)
    {
        return redirect()->action([self::class, 'index'])
            ->with('flash', $bank->name . ' deleted.');
    }

    public function restore($bankSlug)
    {
        $retrieve = Bank::onlyTrashed()->where('slug', $bankSlug)->first();
        $retrieve->restore();

        return redirect()->action([self::class, 'index'])
            ->with('flash', $retrieve->name . ' has been restored.');
    }

    public function search(SearchRequest $request)
    {
        $q = $request->input('q');

        $banks = Bank::query()
            ->where('name', 'LIKE', '%' . $q . '%')
            ->get();

        $archived = Bank::onlyTrashed()
            ->where('name', 'LIKE', '%' . $q . '%')
            ->get();

        $all = $banks->merge($archived);

        session()->flash(
            'flash',
            $all->count() . ' ' . Str::plural('result', $all->count()) . '  found.'
        );

        return view('banks.index', compact('banks', 'archived'));
    }
}

resources/views/banks/_transactions.blade.php
<tr>
    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        {{ $bankTransaction->date->format('M j, Y') }}
    </td>

    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        @if($bankTransaction->is_recorded)
            {{--            {{ dd($bankTransaction->journal->first()) }}--}}
            <a href="{{ route('journals.show', $bankTransaction->journal->first()) }}">
                {{ $bankTransaction->description }}
            </a>
        @else
            <a href="{{ route('bank-transactions.journals.create', $bankTransaction) }}">
                {{ $bankTransaction->description }}
            </a>
        @endif

    </td>
    {{--    <a href="journals/create/{{ $bankTransaction }}">--}}
    {{--        {{ $bankTransaction->description }}--}}
    {{--    </a>--}}

    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        {{ number_format($bankTransaction->debit, 2) }}
    </td>

    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        {{ number_format($bankTransaction->credit, 2) }}
    </td>

    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        {{ number_format($bankTransaction->balance, 2) }}
    </td>
    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
        <toggle-update
            :checked="{{ $bankTransaction->is_recorded ? 'true' : 'false' }}"
            :route="'banks'"
            :model="{{ $bank }}"
            :toggleable="false"
        >
        </toggle-update>
    </td>
{{--    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">--}}
{{--        @if($bankTransaction->is_recorded && $bankTransaction->is_reconciled)--}}
{{--            Reconciled <a href="">View</a>--}}
{{--        @elseif($bankTransaction->is_recorded && ! $bankTransaction->is_reconciled)--}}
{{--            <a href="" class="">Reconcile</a>--}}
{{--        @endif--}}
{{--    </td>--}}

</tr>

resources/views/banks/create.blade.php
<x-layout>
    <x-page-header>
        <div class="my-1">
            <h5 class="text-xl font-thin text-primary">
                Create New Bank Account
            </h5>
            <p class="max-w-2xl text-xs text-gray-500 text-left">
                <a href="{{ route('banks.index') }}" class="focus:outline-none"><i
                        class="fas fa-arrow-left focus:outline-none"></i> Back to All Banks</a>
            </p>
        </div>
    </x-page-header>

    <x-container>
        <form action="{{ route('banks.store') }}" method="POST" autocomplete="off">
            @csrf
            <input type="hidden" autocomplete="false">
            <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                <div class="flex w-full justify-end items-center p-4">
                    <div class="flex">
                        <button class="flex bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none">
                            <div class="py-2 px-4 text-white font-bold">
                                Save
                            </div>
                            <div class="bg-white px-3 flex flex-shrink-0 py-3">
                                <i class="far fa-save fa-lg text-primary"></i>
                            </div>
                        </button>
                    </div>
                </div>

                <div class="border-t border-gray-200">
                    <dl>
                        <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                            <dt class="text-xs font-medium text-gray-500">

                            </dt>
                            <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                                <x-input
                                    name="name"
                                    placeholder=" "
                                    label="Bank name"
                                    width="w-11/12 p-2"
                                    value="{{ old('name') }}"
                                ></x-input>
                            </dd>
                        </div>
                        <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                            <dt class="text-xs font-medium text-gray-500">

                            </dt>
                            <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                                <x-input
                                    name="account_number"
                                    placeholder=" "
                                    label="Account Number"
                                    width="w-11/12 p-2"
                                    value="{{ old('account_number') }}"
                                ></x-input>
                            </dd>
                        </div>
                        <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                            <dt class="text-xs font-medium text-gray-500">

                            </dt>
                            <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                                <x-input
                                    name="account_name"
                                    placeholder=" "
                                    label="Account Name"
                                    width="w-11/12 p-2"
                                    value="{{ old('account_name') }}"
                                ></x-input>
                            </dd>
                        </div>
                    </dl>
                </div>
            </div>
        </form>
    </x-container>
</x-layout>

resources/views/banks/edit.blade.php
<x-layout>
    <x-page-header>
        <div class="my-1">
            <h5 class="text-xl font-thin text-primary">
                {{ ucfirst($bank->name) }}
            </h5>
            <p class="max-w-2xl text-xs text-gray-500 text-left">
                <a href="{{ route('banks.index') }}" class="focus:outline-none"><i class="fas fa-arrow-left focus:outline-none"></i> Back to All Banks</a>
            </p>
        </div>
    </x-page-header>

    <x-container>
        <form action="{{ route('banks.update', $bank) }}" method="POST" autocomplete="off">
            @csrf @method('PUT')
            <input type="hidden" autocomplete="false">
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            <div class="flex w-full justify-end items-center p-4">
                <div class="flex">
                    <button
                        class="flex bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none">
                        <div class="py-1 px-4 text-white font-bold">
                            Save
                        </div>
                        <div class="bg-white px-3 flex flex-shrink-0 py-3">
                            <i class="far fa-save fa-lg text-primary"></i>
                        </div>
                    </button>
                </div>
            </div>
            <div class="border-t border-gray-200">
                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            name="name"
                            placeholder=" "
                            label="Bank Name"
                            width="w-11/12 p-2"
                            value="{{ old('name') ? old('name') : $bank->name }}"
                        ></x-input>
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            name="account_number"
                            placeholder=" "
                            label="Account Number"
                            width="w-11/12 p-2"
                            value="{{ old('account_number') ? old('account_number') : $bank->account_number }}"
                            error="{{ $errors->first('account_number') }}"
                        ></x-input>
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            name="account_name"
                            placeholder=" "
                            label="Account Name"
                            width="w-11/12 p-2"
                            value="{{ old('account_name') ? old('account_name') : $bank->account_name }}"
                            error="{{ $errors->first('account_name') }}"
                        ></x-input>
                    </div>
                </div>
            </div>
        </div>
        </form>
    </x-container>

    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
                <th scope="col" colspan="3"
                    class="px-2 md:px-6 py-3 text-left text-gray-500 uppercase tracking-tighter text-sm font-bolder">
                    Activity Logs
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($bank->activities as $activity)
                @include('partials._activities-list')
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-4 whitespace-nowrap">
                        <div class="flex items-center">
                            <div class="ml-4 text-xs">
                                No activities yet.
                            </div>
                        </div>
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>
</x-layout>

resources/views/banks/show.blade.php
<x-layout>
    <x-page-header>
        <div class="my-1">
            <h5 class="text-xl font-thin text-primary">
                {{ ucfirst($bank->name) }}
            </h5>
            <p class="max-w-2xl text-xs text-gray-500 text-left">
                <a href="{{ route('banks.index') }}" class="focus:outline-none"><i class="fas fa-arrow-left"></i> Back to All Banks</a>
            </p>
        </div>
    </x-page-header>
    @if (session()->has('flash'))
        {{ session()->get('flash') }}
    @endif
    <x-container>
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            <div class="flex w-full justify-end items-center p-4">
                <div class="flex space-x-4 relative">
                    <a href="{{ route('banks.edit', $bank) }}" class="flex flex-shrink-0 flex-grow-0 bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none">
                        <div class="py-2 px-4 text-white font-bold">
                            Update
                        </div>
                        <div class="bg-white px-3 flex flex-shrink-0 py-3">
                            <i class="far fa-edit fa-lg text-primary"></i>
                        </div>
                    </a>

                    <form action="{{ route('banks.destroy', $bank) }}" method="POST" class="group">
                        @csrf @method('DELETE')
                        <button class="flex bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none" {{ $bank->transactions ? 'disabled' : '' }}>
                            <div class="py-2 px-4 text-white font-bold">
                                Delete
                            </div>
                            <div class="bg-white px-3 flex flex-shrink-0 py-3">
                                <i class="far fa-trash-alt fa-lg text-primary"></i>
                            </div>
                        </button>
                        <div class="opacity-0 mb-6 group-hover:opacity-100 duration-300 absolute top-11 bg-primaryLighter text-white p-2 rounded-md w-72 right-0">
                            <small>To delete, please make sure this has no transactions.</small>
                        </div>
                    </form>
                </div>
            </div>

            <div class="border-t border-gray-200">
                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            name="name"
                            placeholder=" "
                            label="Bank Name"
                            width="w-11/12 p-2"
                            readonly="readonly"
                            value="{{ $bank->name }}"
                        ></x-input>
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            name="particulars"
                            placeholder=" "
                            label="Particulars"
                            width="w-11/12 p-2"
                            readonly="readonly"
                            value="{{ $bank->account_number }}"
                        ></x-input>
                    </div>
                </div>

                <div class="p-4 grid grid-cols-3 gap-4">
                    <div class="sm:mt-0 col-span-3 md:col-span-2 md:col-start-2 w-full">
                        <x-input
                            name="account_name"
                            placeholder=" "
                            label="Account Name"
                            width="w-11/12 p-2"
                            readonly="readonly"
                            value="{{ $bank->account_name }}"
                        ></x-input>
                    </div>
                </div>
            </div>
        </div>
    </x-container>

    <x-container>
        {{--slot begins here --}}
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            <div class="flex w-full justify-end items-center p-4">
                <div class="flex">
                    <form action="{{ url('bank-transactions') }}" method="POST" enctype="multipart/form-data" class="flex space-x-4">
                        @csrf
                        <div class="relative w-36 text-center mx-auto">
                              <span class="relative z-0 inline-block w-full border border-primary text-gray-00 p-1 text-sm">
                                Select Bank Statement
                              </span>
                            <input type="file" name="file" class="inline-block absolute z-1 w-full top-0 left-0 opacity-0 cursor-pointer" placeholder="Upload File">

                            @if ($errors->has('file'))
                                <small class="text-red-400 mx-2">{{ $errors->first('file') }}</small>
                            @endif
                        </div>

                        <input type="hidden" value="{{ $bank->id }}" name="bank_id">

                        <button class="flex bg-primary rounded-xl overflow-hidden border border-primary shadow-lg focus:outline-none">
                            <div class="py-2 px-4 text-white font-bold">
                                Upload
                            </div>
                            <div class="bg-white px-3 flex flex-shrink-0 py-3">
                                <i class="fas fa-upload fa-lg text-primary"></i>
                            </div>
                        </button>
                    </form>
                </div>
            </div>
            <table class="min-w-full divide-y divide-gray-200 text-xs">
                <thead class="bg-gray-100">
                <tr class="font-bolder text-left tracking-wider uppercase text-gray-700">
                    <th scope="col" class="px-2 md:px-6 py-3">
                        Date
                    </th>
                    <th scope="col" class="px-2 md:px-6 py-3">
                        Description
                    </th>
                    <th scope="col" class="px-2 md:px-6 py-3">
                        Debit
                    </th>
                    <th scope="col" class="px-2 md:px-6 py-3">
                        Credit
                    </th>
                    <th scope="col" class="px-2 md:px-6 py-3">
                        Balance
                    </th>
                    <th scope="col" class="px-2 md:px-6 py-3">
                        Recorded?
                    </th>
                    <th scope="col" class="px-2 md:px-6 py-3">

                    </th>
                </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                @forelse ($bank->transactions as $bankTransaction)
                    @include('banks._transactions')
                @empty
                    <tr>
                        <td class="px-2 md:px-6 py-2 whitespace-nowrap" colspan="4">
                            No data yet.
                        </td>
                    </tr>
                @endforelse

                </tbody>
            </table>
        </div>

        {{--slot ends here --}}
    </x-container>

    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
                <th scope="col" colspan="3"
                    class="px-2 md:px-6 py-3 text-left text-gray-500 uppercase tracking-tighter text-sm font-bolder">
                    Activity Logs
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($bank->activities as $activity)
                @include('partials._activities-list')
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-4 whitespace-nowrap">
                        <div class="flex items-center">
                            <div class="ml-4 text-xs">
                                No activities yet.
                            </div>
                        </div>
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>
</x-layout>