routes/web.php
<?php

use App\Http\Controllers\AbilityController;
use App\Http\Controllers\BankController;
use App\Http\Controllers\BankTransactionController;
use App\Http\Controllers\BrokerController;
use App\Http\Controllers\CashController;
use App\Http\Controllers\CashTransactionController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\ClassificationController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JournalController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\StockTransactionController;
use App\Http\Controllers\ThirdPartyController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::view('/authenticate', 'auth.authenticate');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::view('/', 'home');

Route::resource('/abilities', AbilityController::class);
    Route::post('/abilities/search', [AbilityController::class, 'search'])->name('abilities.search');
    Route::get('/abilities/{abilitySlug}/restore', [AbilityController::class, 'restore'])->name('abilities.restore');

Route::resource('/roles', RoleController::class);
Route::get('/abilities/{roleSlug}/restore', [RoleController::class, 'restore'])->name('abilities.restore');

Route::resource('users', UserController::class);
    Route::post('/users/search', [UserController::class, 'search'])->name('users.search');
    Route::get('/users/{userSlug}/restore', [UserController::class, 'restore'])->name('users.restore');

Route::resource('/categories', CategoryController::class);
Route::resource('/classifications', ClassificationController::class);

Route::resource('/expenses', ExpenseController::class);
    Route::post('/expenses/search', [ExpenseController::class, 'search'])->name('expenses.search');

//Route::resource('/cash', CashController::class);
Route::get('/cash-transactions/receive', [CashTransactionController::class, 'receive']);
Route::get('/cash-transactions/create', [CashTransactionController::class, 'create']);
Route::resource('/cash-transactions', CashTransactionController::class)->only(['index', 'show']);
Route::resource('/banks', BankController::class);

Route::resource('banks', BankController::class);
    Route::post('/banks/search', [BankController::class, 'search'])->name('banks.search');
    Route::get('/banks/{bankSlug}/restore', [BankController::class, 'restore'])->name('banks.restore');

    Route::post('bank-transactions', BankTransactionController::class);
    Route::get('bank-transactions/{id}/create-journal', [JournalController::class, 'create'])
        ->name('bank-transactions.journals.create');

Route::resource('journals', JournalController::class);

Route::view('stock-transaction/buy', 'stocks.buy')->name('stock-transaction.buy.create');
//Route::post('stock-transaction/buy', [StockTransactionController::class, 'buy'])->name('stock-transaction.buy.store');
Route::view('stock-transaction/sell', 'stocks.sell')->name('stock-transaction.sell.create');
//Route::post('stock-transaction/sell', [StockTransactionController::class, 'sell'])->name('stock-transaction.sell.store');

Route::post('vendors', [ThirdPartyController::class, 'store']);

Route::resource('stock-transaction', StockTransactionController::class);
Route::resource('stocks', StockController::class)->only(['index', 'create', 'show', 'update']);
Route::resource('brokers', BrokerController::class)->only(['store']);

Route::view('profile', 'profile.show');

app/Models/Classification.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Classification extends Model
{
    use HasFactory, SoftDeletes, RecordsActivity;

    protected $guarded = [];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function activities()
    {
        return $this->morphMany(Activity::class, 'subject');
    }

    public function expenses()
    {
        return $this->hasMany(Expense::class,'classification');
    }
}

app/Http/Controllers/Api/ClassificationController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Classification;

class ClassificationController extends Controller
{
    /**
     * Remove the specified resource from storage.
     *
     * @param $id
     * @return void
     */
    public function destroy($id)
    {
        $model = Classification::find($id);

        $model->delete();
    }

    public function restore($id)
    {
        $model = Classification::onlyTrashed()->where('id', $id)->first();
        $model->restore();

        return response()->json(['name' => $model->name], '200');
    }
}

app/Http/Controllers/ClassificationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SearchRequest;
use App\Http\Requests\StoreClassificationRequest;
use App\Models\Activity;
use App\Models\Classification;
use App\Models\Expense;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Str;

class ClassificationController extends Controller
{
    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     * @throws AuthorizationException
     */
    public function index()
    {
        $this->authorize('view-any-classification');

        $classifications = Classification::withTrashed()->latest()->paginate(config('expenses.paginate_count'));

        $activities = Activity::query()->where('subject_type', 'App\Models\Classification')->paginate(config('expenses.paginate_count'));

        return view('classifications.index', compact('classifications', 'activities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|View|Response
     * @throws AuthorizationException
     */
    public function create()
    {
        $this->authorize('create-classification');

        return view('classifications.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreClassificationRequest $request
     * @return JsonResponse
     * @throws AuthorizationException
     */
    public function store(StoreClassificationRequest $request)
    {
        $this->authorize('create-classification');

        Classification::create([
            'user_id' => auth('web')->id(),
            'name' => ucfirst(strtolower($request->name)),
            'slug' => Str::slug($request->name),
        ]);

        return response()->json(['message' => 'Classification added'], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param Classification $classification
     * @return Application|Factory|View|Response
     * @throws AuthorizationException
     */
    public function show(Classification $classification)
    {
        $this->authorize('view-classification');

        return view('classifications.show', compact('classification'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Classification $classification
     * @return Application|Factory|View|Response
     * @throws AuthorizationException
     */
    public function edit(Classification $classification)
    {
        $this->authorize('update-classification');

        return view('classifications.edit', compact('classification'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param StoreClassificationRequest $request
     * @param Classification $classification
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function update(StoreClassificationRequest $request, Classification $classification)
    {
        $this->authorize('update-classification');

        $relatedExpenses = Expense::query()->where('classification', $classification->name)->get();

        $classification->update([
            'name' => ucfirst(strtolower($request->name)),
            'slug' => Str::slug($request->name),
        ]);

        $relatedExpenses->each(function($expense) use ($classification) {
            $expense->update(['classification' => $classification->name]);
        });

        return redirect()->action([self::class, 'show'], $classification)
            ->with('flash', 'Classification has been updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Classification $classification
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function destroy(Classification $classification)
    {
        $this->authorize('delete-classification');

        $classification->delete();

        return redirect()->action([self::class, 'index'])
            ->with('flash', $classification->name . ' has been deleted.');
    }

    public function search(SearchRequest $request)
    {
        $q = $request->input('q');

        $classifications = Classification::query()
            ->where('name', 'LIKE', '%' . $q . '%')
            ->paginate(config('expenses.paginate_count'));

        $count = $classifications->count();

        session()->flash(
            'flash',
            $count . ' ' . Str::plural('result', $count) . '  found.'
        );

        $activities = Activity::query()
            ->where('subject_type', 'App\Models\Classification')
            ->paginate(config('expenses.paginate_count'));

        return view('classifications.index', compact('classifications', 'count', 'activities'));
    }
}

resources/views/classifications/edit.blade.php
<x-layout>
    <x-page-header>
        <div class="my-1">
            <h5 class="text-xl font-thin text-primary">
                Updating {{ $classification->name }}
            </h5>
            <p class="max-w-2xl text-xs text-gray-500 text-left">
                <a href="{{ route('classifications.index') }}" class="focus:outline-none"><i class="fas fa-arrow-left"></i> Back to All Classifications</a>
            </p>
        </div>
    </x-page-header>

    <x-container>
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            <div class="flex w-full justify-end items-center p-4">
                <toggle-button
                    :deleted="{{ $classification->trashed() ? 'true' : 'false' }}"
                    :route="'classifications'"
                    :model="{{ $classification }}"
                ></toggle-button>
            </div>

            <div class="border-t border-gray-200">
                <dl>
                    <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Name
                        </dt>
                        <form action="{{ route('classifications.update', $classification) }}" method="post" class="col-span-2">
                            @csrf @method('PUT')
                            <dd class="text-xs text-gray-900 sm:mt-0 flex">
                                <input
                                    name="name"
                                    placeholder=" "
                                    class="w-11/12 p-2 focus:outline-none"
                                    value="{{ old('name') ? old('name') : $classification->name }}"
                                />

                                <button class="md:mx-2 focus:outline-none">
                                    <i class="far fa-save py-2 px-3 shadow-sm bg-red-700 text-white rounded-sm"></i>
                                </button>
                            </dd>
                        </form>
                    </div>
                    <div class="bg-white p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Slug
                        </dt>
                        <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                            {{ $classification->slug }}
                        </dd>
                    </div>
                    <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Created
                        </dt>
                        <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                            {{ $classification->created_at->diffForHumans() }}
                        </dd>
                    </div>
                    <div class="bg-white p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Updated
                        </dt>
                        <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                            {{ $classification->updated_at->diffForHumans() }}
                        </dd>
                    </div>
                </dl>
            </div>
        </div>
    </x-container>

    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
                <th scope="col" colspan="3"
                    class="px-2 md:px-6 py-3 text-left text-gray-500 uppercase tracking-tighter text-sm font-bolder">
                    Activity Logs
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($classification->activities as $activity)
                @include('partials._activities-list')
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-4 whitespace-nowrap">
                        <div class="flex items-center">
                            <div class="ml-4 text-xs">
                                No activities yet.
                            </div>
                        </div>
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>
</x-layout>

resources/views/classifications/index.blade.php
<x-layout>
    <x-page-header>
        <div class="my-4">
            <h5 class="text-xl font-thin text-primary">
                <a href="{{ route('classifications.index') }}" class="focus:outline-none pl-2">Classifications</a>
            </h5>
            <x-search-form action="/classifications/search" method="POST" role="search"/>
        </div>
        <create :model="'category'" :route="'/classifications'"></create>
    </x-page-header>

    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200 text-xs">
            <thead class="bg-gray-100">
            <tr class="font-bolder text-left tracking-wider uppercase text-gray-700">
                <th scope="col" class="px-2 md:px-6 py-3">
                    Name
                </th>
                <th scope="col" class="px-2 md:px-6 py-3">
                    Slug
                </th>
                <th scope="col" class="px-2 md:px-6 py-3">
                    Active
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($classifications as $classification)
                <tr>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap">
                        <div class="flex items-center">
                            <div>
                                <div class="">
                                    <a class="focus:outline-none"
                                       href="{{ $classification->trashed() ? '' : route('classifications.show', $classification) }}">
                                        {{ ucfirst($classification->name) }}
                                    </a>
                                </div>
                                <div class="text-gray-500">
                                    <small> Created {{ $classification->created_at->diffForHumans() }}</small>
                                </div>
                            </div>
                        </div>
                    </td>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
                        {{ $classification->slug }}
                    </td>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-gray-500">
                        <toggle-button
                            :deleted="{{ $classification->trashed() ? 'true' : 'false' }}"
                            :route="'classifications'"
                            :model="{{ $classification }}"
                        ></toggle-button>
                    </td>
                </tr>
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap" colspan="4">
                        No data yet.
                    </td>
                </tr>
            @endforelse

            @if($classifications->hasPages())
                <x-paginator
                    count="{{ $classifications->count() }}"
                    model="classifications"
                    hasNextPage="{{ $classifications->hasMorePages() }}"
                    currentPage="{{ $classifications->currentPage() }}"
                    nextPageUrl="{{ $classifications->nextPageUrl() }}"
                    prevPageUrl="{{ $classifications->previousPageUrl() }}"
                >
                </x-paginator>
            @endif

            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>

    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
                <th scope="col" colspan="3"
                    class="px-2 md:px-6 py-3 text-left text-gray-500 uppercase tracking-tighter text-sm font-bolder">
                    Activity Logs
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($activities as $activity)
                @include('partials._activities-list')
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap text-xs" colspan="3">
                        No activities yet.
                    </td>
                </tr>
            @endforelse
            @if($activities->hasPages())
                <tr class="font-bolder text-left tracking-wider uppercase text-gray-700 text-sm">
                    <td class="px-2 md:px-6 py-2 whitespace-nowrap" colspan="3">
                        {{ $activities->links() }}
                    </td>
                </tr>
            @endif
            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>
</x-layout>

resources/views/classifications/show.blade.php
<x-layout>
    <x-page-header>
        <div class="my-1">
            <h5 class="text-xl font-thin text-primary">
                {{ ucfirst($classification->name) }}
            </h5>
            <p class="max-w-2xl text-xs text-gray-500 text-left">
                <a href="{{ route('classifications.index') }}" class="focus:outline-none"><i class="fas fa-arrow-left"></i> Back to All Classifications</a>
            </p>
        </div>
    </x-page-header>

    <x-container>
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            <div class="flex w-full justify-end items-center p-4">
                <div class="flex">
                    <p class="shadow-sm mx-2">
                        <a href="{{ route('classifications.edit', $classification) }}" class="focus:outline-none">
                            <i class="far fa-edit py-2 px-3 shadow-sm bg-red-700 text-white rounded-sm"></i>
                        </a>
                    </p>
                    <form action="{{ route('classifications.destroy', $classification) }}" method="POST">
                        @csrf @method('DELETE')
                        <button class="shadow-sm focus:outline-none"><i class="far fa-trash-alt py-2 px-4 shadow-sm bg-gray-100 rounded-sm"></i></button>
                    </form>
                </div>
            </div>

            <div class="border-t border-gray-200">
                <dl>
                    <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Name
                        </dt>
                        <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                            {{ $classification->name }}
                        </dd>
                    </div>
                    <div class="bg-white p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Slug
                        </dt>
                        <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                            {{ $classification->slug }}
                        </dd>
                    </div>
                    <div class="bg-gray-50 p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Created At
                        </dt>
                        <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                            {{ $classification->created_at->diffForHumans() }}
                        </dd>
                    </div>
                    <div class="bg-white p-4 grid grid-cols-3 gap-4">
                        <dt class="text-xs font-medium text-gray-500">
                            Updated
                        </dt>
                        <dd class="text-xs text-gray-900 sm:mt-0 col-span-2">
                            {{ $classification->updated_at->diffForHumans() }}
                        </dd>
                    </div>
                </dl>
            </div>
        </div>
    </x-container>

    <x-container>
        {{--slot begins here --}}
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50">
            <tr>
                <th scope="col" colspan="3"
                    class="px-2 md:px-6 py-3 text-left text-gray-500 uppercase tracking-tighter text-sm font-bolder">
                    Activity Logs
                </th>
            </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            @forelse ($classification->activities as $activity)
                @include('partials._activities-list')
            @empty
                <tr>
                    <td class="px-2 md:px-6 py-4 whitespace-nowrap">
                        <div class="flex items-center">
                            <div class="ml-4 text-xs">
                                No activities yet.
                            </div>
                        </div>
                    </td>
                </tr>
            @endforelse
            </tbody>
        </table>
        {{--slot ends here --}}
    </x-container>
</x-layout>